package com.thfund.client.router.compiler;

/**
 * @author ThomasWang
 * @since 2017/5/28 23:21
 */

public class Constants {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "ThRouter";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY THROUTER.";


    // Java type
    private static final String LANG = "java.lang";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String STRING = LANG + ".String";

    // Custom interface
    private static final String FACADE_PACKAGE = "com.thfund.client.throuter.api.facade";
    private static final String TEMPLATE_PACKAGE = ".template";
    public static final String I_ACTIVITY_ROUTE = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IActivityRoute";
    public static final String I_ACTIVITY_FORMER_ROUTE = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IActivityFormerRoute";

    // Log
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    // Annotation type
    public static final String ANNOTATION_NANE_ACTIVITY_ROUTE= "ActivityRoute";
    public static final String ANNOTATION_NANE_ACTIVITY_FORMER_ROUTE= "ActivityFormerRoute";
    public static final String ANNOTATION_TYPE_ACTIVITY_ROUTE= "com.thfund.client.router.annotation.ActivityRoute";
    public static final String ANNOTATION_TYPE_FRAGMENT_ROUTE= "com.thfund.client.router.annotation.FragmentRoute";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String PARCELABLE = "android.os.Parcelable";
}
